### ISSUE TITLE
EasedLerp extension methods for vectors

### ISSUE THREAD

**Issue by oxysoft** [TobiasWehrum/unity-utilities#1]
Add extension methods to Vector3 for EasedLerpFactor so that we can do

```
follower.position = Vector3.EasedLerp(follower.position, mousePositionWorld, 0.75f);
```

instead of 

```
float t = MathHelper.EasedLerpFactor(0.75f);
follower.position = Vector3.Lerp(follower.position, mousePositionWorld, t);
```

The same should be done for Vector2, and it would be handy too to add a EasedLerp method to MathHelper to perform the same lerping operation for single numbers.

e.g.

```
foo = MathHelper.EasedLerp(foo, targetFoo, 0.75f);
```

**Comment by TobiasWehrum** [comment]
I'm pretty sure I can't add static methods to existing unity classes, but adding those to MathHelper/UnityHelper sounds good to me.

**Comment by oxysoft** [comment]
Oh right good point, didn't think of that. What you could do is make it an instance method then

```
follower.position = follower.position.EasedLerp(mousePositionWorld, 0.75f);
```

**Comment by TobiasWehrum** [comment]
I wanted to stay as close to the existing lerp notation as possible.

Added:
- MathHelper.EasedLerp
- UnityHelper.EasedLerpVector2
- UnityHelper.EasedLerpVector3
- UnityHelper.EasedLerpVector4
- UnityHelper.EasedLerpColor
