### ISSUE TITLE
Singleton doesnt release its static reference

### ISSUE THREAD

**Issue by TJHeuvel** [TobiasWehrum/unity-utilities#2]
You should set the instance value of your singleton to null when the object is destroyed (and its this reference). If you fail to do this the object will not be garbage collected and any references to unity assets wont be unloaded.

**Comment by TobiasWehrum** [comment]
Clearly. Thanks for catching that. Guess I'll have to make a virtual OnDestroy() method.

(I wish I wouldn't have to. Having to check whether a parent class overloads any default Unity methods to differentiate between the automagic "void OnDestroy()" and "protected override void OnDestroy()" is always such a bother.)

**Comment by TobiasWehrum** [comment]
Fixed.
